version: '3.1'

volumes:
  init-db:
    driver: local
  data-db:
    driver: local

services:
  mongodb:
    image: mongo:7.0.0-rc8-jammy
    restart: always
    volumes:
      - ./mongo_data_bootstrap/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: customermgmt
      MONGODB_HOSTNAME: mongodb
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass

  customerapi:
    build:
      context: customerapi
      dockerfile: Dockerfile
    container_name: ironhome-customerapi
    image: customerapi:latest
    restart: always
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: customermgmt
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: mongoadmin
      MONGODB_HOSTNAME: mongodb
    ports:
      - "5000:5000"
    depends_on:
      - mongodb